spring:
  application:
    name: library-service
  datasource:
    url: jdbc:mysql://localhost:3306/library
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password


